# Generated by Django 3.2 on 2024-04-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.IntegerField(unique=True)),
                ('CustomerName', models.CharField(max_length=25)),
                ('BillingAddress', models.TextField()),
                ('ShippingAddress', models.TextField()),
                ('GSTIN', models.CharField(max_length=20)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=250)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='api.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='BillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_sundry_name', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_sundry', to='api.invoice')),
            ],
        ),
    ]
